apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-mqttx-cli
spec:
  selector:
    matchLabels:
      app: mqtt-mqttx-cli
  replicas: 1 
  template: 
    metadata:
      labels:
        app: mqtt-mqttx-cli
    spec:
      containers:
      - name: mqttx-cli
        image: emqx/mqttx-cli
        command: [ "/bin/sh" , "-c" ]
        args: 
          - "mqttx --version"
          - "tail -f /dev/null"